import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

from app.core.config import settings
from app.db import Base

# Imported for the side effect: a model that is never imported is not in
# `Base.metadata`, and autogenerate would read its whole table as one somebody
# dropped. The package's `__init__` imports every model, so this one line is
# what keeps the comparison complete — naming modules individually was a list
# that the next model had to be remembered into.
import app.models  # noqa: F401,E402

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def include_object(
    obj: object, name: str | None, type_: str, reflected: bool, compare_to: object
) -> bool:
    """Which schema objects autogenerate is allowed to have an opinion about.

    Check constraints are excluded, and only because Alembic cannot compare the
    ones this schema has. `stored_by_value` builds its columns with
    `Enum(create_constraint=True)`, so the `chat_type`, `message_visibility` and
    `participant_role` checks are **type-bound** — they belong to the type
    rather than to the table — and Alembic filters type-bound constraints out of
    the metadata side of the comparison on purpose. The reflected ones then have
    nothing to match against, and every run reports all three as removed.

    The cost of leaving that in place is not a red line in CI. It is that
    `alembic revision --autogenerate` emits `op.drop_constraint` for all three,
    so the next person to generate a migration gets one that quietly deletes the
    schema's only guarantee about which enum values are legal — and has to know
    to delete those lines by hand.

    This is a suppression, not a fix, and it hides a real edit to one of those
    constraints along with the noise. That trade is worth making while the only
    check constraints here are generated by `stored_by_value`: a change to one
    of those is a change to a `StrEnum` in `app/models/`, which is a code review,
    not something autogenerate was going to catch. A hand-written check
    constraint would be the moment to revisit it.
    """
    return type_ != "check_constraint"


# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""

    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
